services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fluxtrader
      POSTGRES_USER: fluxtrader
      POSTGRES_PASSWORD: fluxtrader
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fluxtrader']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: infra/Dockerfile.server
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgresql://fluxtrader:fluxtrader@db:5432/fluxtrader
      SESSION_SECRET: devsecret
      DERIV_APP_ID: ${DERIV_APP_ID}
      DERIV_REDIRECT_URI: http://localhost:8080/auth/callback
      VITE_PUBLIC_URL: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'

  web:
    build:
      context: .
      dockerfile: infra/Dockerfile.web
    environment:
      VITE_API_BASE_URL: http://server:8080
      VITE_PUBLIC_URL: http://localhost:5173
    depends_on:
      - server
    ports:
      - '5173:80'

volumes:
  db-data:
