name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install web dependencies
        working-directory: apps/web
        run: npm install
      - name: Run web tests
        working-directory: apps/web
        run: npm run test -- --run
      - name: Install server dependencies
        working-directory: apps/server
        run: npm install
      - name: Run server tests
        working-directory: apps/server
        env:
          NODE_ENV: test
        run: npm run test -- --run
      - name: Lint server
        working-directory: apps/server
        run: npm run lint
      - name: Lint web
        working-directory: apps/web
        run: npm run lint
